openapi: 3.0.0
info:
  title: Composer API
  version: 1.0.0
paths:
  /composers:
    get:
      summary: Find all composers
      tags:
        - Composers
      description: Retrieves and lists all composers in the directory
      responses:
        "200":
          description: |
            Displays a list of all composers
          content:
            application/json:
              schema:
                type: array
                description: An array of composer names
                items:
                  $ref: '#/components/schemas/inline_response_200'
        "500":
          description: |
             Server encountered an internal error 
             and is currently unable to handle your request
        "501":
          description: Server does not support the request
    post:
      summary: Add a new composer
      tags:
        - Composers
      description: Adds a new composer to the directory.
      requestBody:
        description: Composer bio information
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/composers_body'
      responses:
        "200":
          description: |
            The new composer is added to the directory
            Return a message containing the new composer's
            name, start date, and id
          content:
            application/json:
              schema:
                type: array
                description: Composer's name, start date, and API generated id
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
        "500":
          description: |
            Server encountered an internal error 
            and is currently unable to handle your request
        "501":
          description: Server does not support the request
             
  /composers/{id}:
    get:
      summary: Finds a composer by id
      tags:
        - Composers
      description: Retrieves and displays any composer's name and bio who is in the directory by their id
      parameters:
      - name: id
        in: path
        description: |
          A unique identifier generated
          and assigned to each composer
          by the API
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: |
            Displays the composer's
            name and bio that matches
            the id entered
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_2'
        "500":
          description: |
            Server encountered an unexpected error 
            and is currently unable to handle your request
        "501":
          description: Server does not support the request 
components:
  schemas:
    inline_response_200:
      required:
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
    composers_body:
      required:
      - firstName
      - lastName
      - recordStartDate
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
        placeOfBirth:
          type: string
        recordStartDate:
          type: string
        other:
          type: string
          description: Any additional details the user wishes to add
    inline_response_200_1:
      required:
      - composerId
      - firstName
      - lastName
      - recordStartDate
      type: object
      properties:
        composerId:
          type: string
          description: Unique identifier generated by the API
        firstName:
          type: string
        lastName:
          type: string
        recordStartDate:
          type: string
    inline_response_200_2:
      required:
      - composerId
      - dateOfBirth
      - firstName
      - lastName
      - other
      - placeOfBirth
      - recordStartDate
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
        placeOfBirth:
          type: string
        recordStartDate:
          type: string
        other:
          type: string
          description: Any additional details the user wishes to add
